routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');
Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');


Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->middleware('verified');

Route::resource('users', 'UserController')->middleware('auth');


// Route controller shop*


Route::resource('categories', 'CategoriesController');

Route::resource('products', 'ProductsController');

Route::resource('orderStatuses', 'OrderStatusController');

Route::resource('deliveries', 'DeliveryController');

Route::resource('banners', 'BannerController');

Route::resource('customers', 'CustomerController');

Route::resource('orders', 'OrderController');



// router front end


//trang chu



//Route::get('/trang-chu', 'HomeController@getIndex');

// Route::get('/', function () {
//     return view('clothshop.index');
// });

//Route::get('/loai-sp', function () {
//    return view('clothshop.categories');  //giao diện không thôi thì làm như 3 cái này
//});

// Route::get('/sanpham', function () {
//     return view('clothshop.products');
// });

//Route::get('/dangnhap', function () {
//    return view('clothshop.login');
//});

//Route::get('/taotaikhoan', function () {
//    return view('clothshop.register');
//});

// Route::get('/chitietsp', function () {
//     return view('clothshop.singleproduct');
// });

//Route::get('/giohang', function () {
//    return view('clothshop.shopcart');
//});

Route::get('/diachigiaohang', function () {
    return view('clothshop.shipaddress');
});

Route::get('/hinhthucthanhtoan', function () {
    return view('clothshop.payment');
});

Route::get('/xacnhanthanhtoan', function () {
    return view('clothshop.summary');
});

Route::get('/hoantatdonhang', function () {
    return view('clothshop.finish');
});

Route::get('/thongtin', function () {
    return view('clothshop.about');
})->name('thongtin');

Route::get('/lienhe', function () {
    return view('clothshop.contact');
})->name('lienhe');







Route::get('/', 'PageController@getIndex')->name('trangchu');

Route::get('/sanpham', 'PageController@getProduct')->name('sanpham');

Route::get('/chi-tiet-sanpham/{id}', 'PageController@productDetail')->name('productDetail');

Route::get('/loai-san-pham/{id}', 'PageController@getProductCategories')->name('productCategories');

Route::get('/add-to-cart/{id}', 'PageController@getAddToCart')->name('addToCart');

Route::get('/checkout', 'PageController@getCheckout')->name('checkout');

Route::post('/checkout', 'PageController@postCheckout')->name('checkout');

Route::get('/del-cart/{id}', 'PageController@getDelItemsCart')->name('dellProductCart');

Route::get('/count', 'PageController@count')->name('count');

Route::get('/dashboard', 'PageController@dashboard')->name('dashboard');

resources/views/order_statuses/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Order Status
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">
            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'orderStatuses.store']) !!}

                        @include('order_statuses.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/order_statuses/datatables_actions.blade.php
{!! Form::open(['route' => ['orderStatuses.destroy', $id], 'method' => 'delete']) !!}
<div class='btn-group'>
    <a href="{{ route('orderStatuses.show', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-eye-open"></i>
    </a>
    <a href="{{ route('orderStatuses.edit', $id) }}" class='btn btn-default btn-xs'>
        <i class="glyphicon glyphicon-edit"></i>
    </a>
    {!! Form::button('<i class="glyphicon glyphicon-trash"></i>', [
        'type' => 'submit',
        'class' => 'btn btn-danger btn-xs',
        'onclick' => "return confirm('Are you sure?')"
    ]) !!}
</div>
{!! Form::close() !!}

resources/views/order_statuses/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Order Status
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($orderStatus, ['route' => ['orderStatuses.update', $orderStatus->id], 'method' => 'patch']) !!}

                        @include('order_statuses.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/order_statuses/fields.blade.php
<!-- Name Field -->
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Name:') !!}
    {!! Form::text('name', null, ['class' => 'form-control']) !!}
</div>

<!-- Description Field -->
<div class="form-group col-sm-6">
    {!! Form::label('description', 'Description:') !!}
    {!! Form::text('description', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Save', ['class' => 'btn btn-primary']) !!}
    <a href="{{ route('orderStatuses.index') }}" class="btn btn-default">Cancel</a>
</div>

resources/views/order_statuses/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Order Statuses</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{{ route('orderStatuses.create') }}">Add New</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('order_statuses.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/order_statuses/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Order Status
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('order_statuses.show_fields')
                    <a href="{{ route('orderStatuses.index') }}" class="btn btn-default">Back</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/order_statuses/show_fields.blade.php
<!-- Name Field -->
<div class="form-group">
    {!! Form::label('name', 'Name:') !!}
    <p>{{ $orderStatus->name }}</p>
</div>

<!-- Description Field -->
<div class="form-group">
    {!! Form::label('description', 'Description:') !!}
    <p>{{ $orderStatus->description }}</p>
</div>

<!-- Created At Field -->
<div class="form-group">
    {!! Form::label('created_at', 'Created At:') !!}
    <p>{{ $orderStatus->created_at }}</p>
</div>

<!-- Updated At Field -->
<div class="form-group">
    {!! Form::label('updated_at', 'Updated At:') !!}
    <p>{{ $orderStatus->updated_at }}</p>
</div>

resources/views/order_statuses/table.blade.php
@section('css')
    @include('layouts.datatables_css')
@endsection

{!! $dataTable->table(['width' => '100%', 'class' => 'table table-striped table-bordered']) !!}

@push('scripts')
    @include('layouts.datatables_js')
    {!! $dataTable->scripts() !!}
@endpush